test:
  script:
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - apt-get update -qy
  - apt-get install -y nodejs
  - bundle install --path /cache
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rake test

staging:
  type: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=hartl-stage --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master

production:
  type: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=hartl-rails-tutorial --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - tags
