db:
  container_name: db
  image: postgres
  ports:
   - "5432"
web:
  container_name: web
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - '.:/sample_app'
  ports:
    - "3000:3000"
  links:
    - db
